### ISSUE TITLE
fsockopen error

### ISSUE THREAD

**Issue by ghost** [jdp/redisent#1]
Hi
I think it's a bit of a bug. When the redis server is down

<pre>
$this->__sock = fsockopen($host, $port, $errno, $errstr); 
</pre>

PHP displays a warning before the exception is thrown. 

<pre>
Warning: fsockopen() [function.fsockopen]: unable to connect to localhost:6379 (Connection refused) in ./lib/redisent/redisent.php on line 47
</pre>

I think some checking if the socket exists would help or at least something like this:  

<pre>
$this->__sock = @fsockopen($host, $port, $errno, $errstr);
</pre>

Which is not the bes solition but it works :)
Cheers!

**Comment by jdp** [comment]
I don't think this should make it into master. It would be handled better through your PHP and logging configurations, rather than outright silencing it in the client library.
