### ISSUE TITLE
Infinite loop on broken pipe.

### ISSUE THREAD

**Issue by gumayunov** [jdp/redisent#10]
``` php
        for ($written = 0; $written < strlen($command); $written += $fwrite) {
            $fwrite = fwrite($this->__sock, substr($command, $written));
            if ($fwrite === FALSE) {
                throw new Exception('Failed to write entire command to stream');
            }
        }
```

On broken pipe `fwrite` returns 0 and it loops for ever.

**Comment by jdp** [comment]
Will be fixing this. This same issue is discussed on [the php.net fwrite docs](http://us3.php.net/manual/en/function.fwrite.php#96951), where the example code given is straight-up wrong.
