### ISSUE TITLE
Add support for specifying a socket connect timeout

### ISSUE THREAD

**Issue by rbone** [jdp/redisent#16]
I'm interested in adding support for adding a socket connect timeout and I wanted to get some feedback on your preferred approach for this.

Setting the timeout is relatively straightforward (just one more parameter to fsockopen), my question is really about the best way to pass in the timeout, it could either be done as an extra parameter on the constructor:

``` php
<?php
$redis = new redisent\Redis('redis://localhost:6379', $timeout = 2);
```

Or it could be made a query string parameter on the dsn:

``` php
<?php
$redis = new redisent\Redis('redis://localhost:6379?timeout=2');
```

I'm happy to code it up myself, just let me know which option you prefer.

**Comment by jdp** [comment]
I'd prefer the timeout as an explicit constructor argument, unless there's a precedent in other major projects for setting it in the DSN. Otherwise, I'm all about putting it in the constructor.

**Comment by rbone** [comment]
Cool that works for me, I'll put together a pull request in a bit. Thanks for the feedback.
