### ISSUE TITLE
Constant CRLF already defined

### ISSUE THREAD

**Issue by spencerdeinum** [jdp/redisent#19]
If CRLF has already been defined, then

<pre>define('CRLF', sprintf('%s%s', chr(13), chr(10)));</pre>

in Redisent.php will cause an error and stop execution.

<pre>if( !defined('CRLF') ) define('CRLF', sprintf('%s%s', chr(13), chr(10)));</pre>

This fixes it, and it seems to work but this may be system / code dependant.

**Comment by jdp** [comment]
`CRLF` should always be carriage return and line feed, they are defined as 13 and 10 respectively and aren't system dependent, provided the system uses at least 7-bit ASCII. Also it is defined now in the `redisent` namespace, so there shouldn't be clashes.

**Comment by spencerdeinum** [comment]
I understand, I'm using php-resque and their files seem to be a bit out of date now. They don't have the namespace declared. Thanks for your help! nice job with this lib btw :)
