### ISSUE TITLE
ZADD, ZREM, etc

### ISSUE THREAD

**Issue by ghost** [jdp/redisent#2]
I think adding sortable sets support from Redis 1.2 
Adding 'ZADD', 'ZREM'  to $bulk_cmds worked for me (just using ZADD and ZRANGE currently)
Cheers!

**Comment by ghost** [comment]
:) "I think adding sortable sets support from Redis 1.2" ... would ba kindda useful

**Comment by jdp** [comment]
Thanks to the [Redis Unified Protocol](http://redis.io/topics/protocol) commands no longer need specific handlers. Fixed, in a roundabout way :)
