### ISSUE TITLE
Constant already defined

### ISSUE THREAD

**Issue by WanWizard** [jdp/redisent#26]
Could you check if CRLF is defined as a constant before setting it?

The FuelPHP framework already defines this constant, so our users can not use redisent at the moment.

**Comment by jdp** [comment]
FuelPHP already has a [built-in Redis client](http://fuelphp.com/docs/classes/redis.html) that is largely inspired by Redisent.

**Comment by jdp** [comment]
But I do think it makes sense to fix to avoid conflicts in other environments.

**Comment by WanWizard** [comment]
Fuel v2 will no longer use an internal class, but will use your composer package if configured.

I bumped into this error when I started testing it.

**Comment by jdp** [comment]
@WanWizard Ah I see. We already have a composer config, I'll update Redisent and publish a new package with the  fix included soon.

**Comment by WanWizard** [comment]
I know, I was using that. I meant I was testing our new code using your composer package. Thanks for the fix.

**Comment by jdp** [comment]
Fixed in 8d54bdc7.

**Comment by WanWizard** [comment]
Thanks!
