### ISSUE TITLE
sort command doesn't work as before

### ISSUE THREAD

**Issue by ghost** [jdp/redisent#7]
It was possible to call sort command like this in older versions:
$redis->sort('set_name limit 0 10 desc');
It doesn't work anymore so you have to call sort method like this:
$redis->sort('set_name', 'limit', '0', '10', 'desc');
Is it possible to do something with that?

**Comment by jdp** [comment]
This is because of the switch to the [Redis Unified Protocol](http://redis.io/topics/protocol). I would be open to adding specific methods for the more awkward Redis commands to use.
